### ISSUE TITLE
event/data/previous_attributes is optional in API but mandatory in the case class

### ISSUE THREAD

**Issue by yurique** [outr/scala-stripe#2]
For example `stripe.events.byId(id)` fails with `io.circe.DecodingFailure$$anon$2: Attempt to decode value on failed cursor: DownField(previousAttributes),DownField(data)`

And when parsing an incoming webhook event with `Pickler` the same failure happens. I can workaround the webhook (by adding and empty object, for example), but not the API call. 

![image](https://user-images.githubusercontent.com/919230/44296035-4e8ab800-a2be-11e8-8a17-9e764c381a9e.png)

**Comment by darkfrog26** [comment]
Thanks for the PR. Do you need a new release soon?

**Comment by yurique** [comment]
No rush :)

**Comment by darkfrog26** [comment]
FYI, I've done several updates recently to the library and I'm just now pushing out `1.1.10` as the most recent.  This functionality has been in several of the last released.
